package com.duecare.journey.intel

import com.duecare.journey.intel.DomainKnowledge.CorridorKnowledge
import com.duecare.journey.intel.DomainKnowledge.IloForcedLabourIndicators
import com.duecare.journey.journal.FeePayment
import com.duecare.journey.journal.JournalEntry
import com.duecare.journey.journal.JourneyStage
import com.duecare.journey.journal.Party
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Produces the structured markdown document an NGO caseworker can read
 * in two minutes to understand a worker's situation. Combines:
 *
 *   - Worker context (corridor + current stage)
 *   - ILO indicator coverage with severity
 *   - Fee table (who, what, when, how much, legal/illegal)
 *   - Chronological timeline grouped by stage
 *   - Recommended next steps with NGO referrals
 *
 * The document is markdown so it renders cleanly in any messenger,
 * email, PDF generator, or NGO case-management system. No PII is
 * embedded automatically — the caller can choose to redact party
 * names before exporting.
 */
@Singleton
class NgoReportBuilder @Inject constructor(
    private val timeline: TimelineBuilder,
    private val fees: FeeAggregator,
    private val risks: RiskAnalyzer,
) {

    private val dateFmt = SimpleDateFormat("yyyy-MM-dd", Locale.US)
    private val dateTimeFmt = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US)

    data class Report(
        val markdown: String,
        val summary: Summary,
    )

    data class Summary(
        val corridorCode: String?,
        val totalEntries: Int,
        val totalRisks: Int,
        val criticalRisks: Int,
        val totalFeeLines: Int,
        val illegalFeeLines: Int,
        val ngoContactCount: Int,
        val firstEventDate: String?,
        val lastEventDate: String?,
    )

    fun build(
        entries: List<JournalEntry>,
        feePayments: List<FeePayment>,
        parties: List<Party>,
        currentStage: JourneyStage,
        corridorCode: String?,
    ): Report {
        val tl = timeline.build(entries)
        val allRisks = risks.analyzeAll(entries)
        val histogram = risks.iloIndicatorHistogram(allRisks)
        val feeReport = fees.build(feePayments, parties, entries, corridorCode)
        val corridor = CorridorKnowledge.byCode(corridorCode)

        val sb = StringBuilder()
        sb.appendLine("# Migrant worker case intake")
        sb.appendLine("_Generated by Duecare Journey on ${dateTimeFmt.format(Date())}_")
        sb.appendLine()

        // Header
        sb.appendLine("## 1. Worker context")
        sb.appendLine("- **Corridor:** ${corridor?.code ?: "(not set)"} — " +
            (corridor?.let { "${it.originName} → ${it.destName}" } ?: "(unknown)"))
        sb.appendLine("- **Current stage:** ${stageLabel(currentStage)}")
        sb.appendLine("- **Journal entries:** ${tl.totalEvents}")
        sb.appendLine("- **First entry:** ${tl.firstEventMillis?.let { dateFmt.format(Date(it)) } ?: "(none yet)"}")
        sb.appendLine("- **Most recent entry:** ${tl.lastEventMillis?.let { dateFmt.format(Date(it)) } ?: "(none yet)"}")
        sb.appendLine()

        // Risk summary
        sb.appendLine("## 2. ILO forced-labour indicator coverage")
        if (histogram.isEmpty()) {
            sb.appendLine("_No risk indicators have fired against the journal yet. " +
                "Either the worker's situation does not currently match any " +
                "ILO C029 indicator, OR the journal does not yet contain " +
                "enough detail to analyze. Use the Advice tab to walk through " +
                "guided questions._")
        } else {
            sb.appendLine("| ILO # | Indicator | Times referenced |")
            sb.appendLine("|---|---|---:|")
            histogram.toSortedMap().forEach { (n, count) ->
                val ind = IloForcedLabourIndicators.byNumber(n)
                if (ind != null) {
                    sb.appendLine("| ${ind.number} | ${ind.name} | $count |")
                }
            }
            sb.appendLine()
            sb.appendLine("**Critical-severity flags:** ${tl.criticalRisks}  ")
            sb.appendLine("**All flags:** ${tl.totalRisks}")
        }
        sb.appendLine()

        // Detailed risks
        if (allRisks.isNotEmpty()) {
            sb.appendLine("## 3. Detailed risk findings")
            allRisks.forEachIndexed { i, r ->
                sb.appendLine("### ${i + 1}. ${r.displayName} _(severity: ${r.severity.name})_")
                sb.appendLine("- **Source entry:** \"${r.sourceEntryTitle}\"")
                sb.appendLine("- **Matched phrase:** _\"${r.matchedSnippet}\"_")
                sb.appendLine("- **ILO indicator:** #${r.iloIndicator}")
                sb.appendLine("- **Statute / framework:** ${r.statuteCitation}")
                sb.appendLine("- **What this means:** ${r.whatItMeans}")
                sb.appendLine("- **Recommended next step:** ${r.nextStep}")
                sb.appendLine()
            }
        }

        // Fees
        sb.appendLine("## 4. Fees paid (who, what, when, how much)")
        if (feeReport.lines.isEmpty()) {
            sb.appendLine("_No fee data captured. If money has changed hands, " +
                "use the structured fee-recording flow or add free-text " +
                "entries; this section will populate automatically._")
        } else {
            sb.appendLine("| Date | Recipient | Purpose | Amount | Legality |")
            sb.appendLine("|---|---|---|---:|:---|")
            feeReport.lines.forEach { l ->
                val legal = if (l.isProbablyIllegal) "❗ LIKELY RECOVERABLE" else "✓ within cap"
                sb.appendLine("| ${dateFmt.format(Date(l.paidAtMillis))} | " +
                    "${l.recipientName} | ${l.purposeLabel} | ${l.displayAmount} | $legal |")
            }
            sb.appendLine()
            sb.appendLine("### Totals by currency")
            feeReport.totalsByCurrency.forEach {
                sb.appendLine("- **${it.currency}:** ${it.displayTotal}")
            }
            if (feeReport.illegalLines.isNotEmpty()) {
                sb.appendLine()
                sb.appendLine("### Likely-recoverable totals (illegal fees)")
                feeReport.illegalTotalsByCurrency.forEach {
                    sb.appendLine("- **${it.currency}:** ${it.displayTotal}")
                }
                sb.appendLine()
                sb.appendLine("**Recovery basis:** ${corridor?.placementFeeNote ?: "(no corridor selected)"}")
            }
        }
        sb.appendLine()

        // Timeline
        sb.appendLine("## 5. Chronological timeline")
        if (tl.byStage.isEmpty()) {
            sb.appendLine("_No timeline entries yet._")
        } else {
            tl.byStage.forEach { bucket ->
                sb.appendLine("### ${bucket.stageLabel}")
                bucket.events.forEach { e ->
                    val flag = e.highestSeverity?.let { sev ->
                        when (sev) {
                            DomainKnowledge.GrepRules.Severity.CRITICAL -> " 🚩 CRITICAL"
                            DomainKnowledge.GrepRules.Severity.HIGH -> " ⚠️ HIGH"
                            DomainKnowledge.GrepRules.Severity.MEDIUM -> " · medium"
                            DomainKnowledge.GrepRules.Severity.LOW -> ""
                        }
                    } ?: ""
                    sb.appendLine("- **${e.displayDate}** — ${e.title}$flag")
                    if (e.body.isNotBlank()) {
                        sb.appendLine("    > ${e.body.replace("\n", " ")}")
                    }
                }
                sb.appendLine()
            }
        }

        // Referrals
        sb.appendLine("## 6. Recommended NGO + regulator contacts")
        if (corridor == null) {
            sb.appendLine("_No corridor configured. Set the worker's origin " +
                "and destination during onboarding to populate this section._")
        } else {
            sb.appendLine("### Origin-country regulator")
            sb.appendLine("- **${corridor.originRegulator.name}** — " +
                "${corridor.originRegulator.url}" +
                (corridor.originRegulator.phone?.let { " · $it" } ?: ""))
            sb.appendLine()
            sb.appendLine("### Destination-country regulator")
            sb.appendLine("- **${corridor.destRegulator.name}** — " +
                "${corridor.destRegulator.url}" +
                (corridor.destRegulator.phone?.let { " · $it" } ?: ""))
            sb.appendLine()
            sb.appendLine("### NGOs that handle this corridor")
            corridor.ngoContacts.forEach { c ->
                sb.appendLine("- **${c.name}** — ${c.service}" +
                    (c.phone?.let { " · $it" } ?: "") +
                    (c.url?.let { " · $it" } ?: ""))
            }
        }
        sb.appendLine()

        sb.appendLine("---")
        sb.appendLine("_This report was generated locally on the worker's " +
            "phone by Duecare Journey. The journal data never left the " +
            "device unless the worker chose to share this report._")

        return Report(
            markdown = sb.toString(),
            summary = Summary(
                corridorCode = corridor?.code,
                totalEntries = tl.totalEvents,
                totalRisks = tl.totalRisks,
                criticalRisks = tl.criticalRisks,
                totalFeeLines = feeReport.lines.size,
                illegalFeeLines = feeReport.illegalLines.size,
                ngoContactCount = corridor?.ngoContacts?.size ?: 0,
                firstEventDate = tl.firstEventMillis?.let { dateFmt.format(Date(it)) },
                lastEventDate = tl.lastEventMillis?.let { dateFmt.format(Date(it)) },
            ),
        )
    }

    private fun stageLabel(stage: JourneyStage): String = when (stage) {
        JourneyStage.PRE_DEPARTURE -> "Pre-departure"
        JourneyStage.IN_TRANSIT -> "In transit"
        JourneyStage.ARRIVED -> "Arrived in destination country"
        JourneyStage.EMPLOYED -> "Employed"
        JourneyStage.BETWEEN_EMPLOYERS -> "Between employers (in country)"
        JourneyStage.EXIT -> "Exit / repatriation"
    }
}
